app = "myblog-ysgr6a"
primary_region = "ams"

[build]
  image = "python:3.10"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

