name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Authenticate Flyctl
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN

      - name: Deploy to Fly.io
        run: fly deploy --remote-only
